collections:
  - name: settings
    label: Configurações
    format: json
    files:
      - name: site
        label: Site
        file: content/settings/site.json
        fields:
          - { name: name, label: Nome do site, widget: string, required: true }
          - {
              name: url,
              label: URL do site,
              widget: string,
              required: true,
              pattern: ['^https?://', 'url inválida'],
            }
          - { name: email, label: E-mail, widget: string, required: false }
          - { name: city, label: Cidade, widget: string, required: false }
          - name: countryCode
            label: Código do país
            widget: select
            required: false
            options: [FR, ES, PT, DE, IT, GB, IE, BE, NL]
          - name: social
            label: Social
            widget: list
            required: false
            fields:
              - { name: name, label: Nome, widget: string }
              - {
                  name: url,
                  label: URL,
                  widget: string,
                  pattern: ['^https?://', 'url inválida'],
                }
          - name: nav
            label: Navegação
            widget: list
            required: false
            fields:
              - { name: title, label: Título, widget: string }
              - name: links
                label: Links
                widget: list
                fields:
                  - { name: href, label: Href, widget: string }
                  - { name: label, label: Rótulo, widget: string }
                  - {
                      name: external,
                      label: Externo,
                      widget: boolean,
                      required: false,
                    }
                  - { name: rel, label: Rel, widget: string, required: false }
          - {
              name: footerText,
              label: Texto do rodapé,
              widget: text,
              required: false,
            }
          - {
              name: defaultMetaImage,
              label: Imagem padrão OG,
              widget: image,
              required: false,
            }
